<?php

return [
    [
        'slug' => 'retail-operations-platform',
        'title' => 'Retail Operations Platform',
        'category' => 'Web Application',
        'year' => '2024',
        'client' => 'National Retail Group',
        'summary' => 'A unified operations hub replacing fragmented spreadsheets with real-time inventory, orders, and team workflows.',
        'description' => 'We partnered with a growing retail group to replace legacy tooling with a single Laravel-powered platform. The system connects warehouse teams, store managers, and leadership with live dashboards, automated alerts, and role-based workflows that scale across regions.',
        'cover' => 'images/work-software-development.png',
        'gallery' => [
            ['src' => 'images/work-software-development.png', 'caption' => 'Operations dashboard'],
            ['src' => 'images/work-digital-transformation.png', 'caption' => 'Inventory analytics view'],
            ['src' => 'images/work-it-consulting.png', 'caption' => 'Team workflow board'],
        ],
        'tech_stack' => ['Laravel', 'React', 'PostgreSQL', 'Redis', 'AWS'],
        'services' => ['Web Development', 'Cloud Solutions', 'UI/UX Design'],
        'highlights' => [
            '40% faster order processing across stores',
            'Single source of truth for inventory data',
            'Role-based dashboards for 200+ users',
        ],
    ],
    [
        'slug' => 'saas-analytics-suite',
        'title' => 'SaaS Analytics Suite',
        'category' => 'Data Platform',
        'year' => '2025',
        'client' => 'Growth-stage SaaS Startup',
        'summary' => 'Self-serve analytics with custom dashboards, exports, and usage insights for product and revenue teams.',
        'description' => 'This project delivered a modular analytics layer on top of an existing SaaS product. We designed intuitive dashboard builders, optimized query performance for large datasets, and integrated billing usage metrics so teams could act on product and revenue signals in one place.',
        'cover' => 'images/work-digital-transformation.png',
        'gallery' => [
            ['src' => 'images/work-digital-transformation.png', 'caption' => 'Executive overview'],
            ['src' => 'images/work-software-development.png', 'caption' => 'Custom report builder'],
            ['src' => 'images/work-it-consulting.png', 'caption' => 'Usage insights panel'],
        ],
        'tech_stack' => ['Laravel', 'Vue.js', 'MySQL', 'Tailwind CSS', 'Docker'],
        'services' => ['Web Development', 'Data Analytics', 'Support & Maintenance'],
        'highlights' => [
            'Sub-second dashboard loads at scale',
            'Embedded analytics for enterprise accounts',
            'Automated weekly insight digests',
        ],
    ],
    [
        'slug' => 'field-service-mobile-app',
        'title' => 'Field Service Mobile App',
        'category' => 'Mobile Product',
        'year' => '2023',
        'client' => 'Regional Services Company',
        'summary' => 'Offline-capable mobile app for technicians with scheduling, job sheets, and photo capture in the field.',
        'description' => 'Technicians needed reliable tools that worked without constant connectivity. We built a cross-platform mobile experience with offline sync, digital job sheets, signature capture, and a dispatch console for operations managers to coordinate teams in real time.',
        'cover' => 'images/work-it-consulting.png',
        'gallery' => [
            ['src' => 'images/work-it-consulting.png', 'caption' => 'Technician job view'],
            ['src' => 'images/work-software-development.png', 'caption' => 'Dispatch console'],
            ['src' => 'images/work-digital-transformation.png', 'caption' => 'Completion reporting'],
        ],
        'tech_stack' => ['React Native', 'Laravel API', 'MySQL', 'Firebase', 'AWS S3'],
        'services' => ['Mobile Apps', 'Web Development', 'Cloud Solutions'],
        'highlights' => [
            'Offline-first sync for remote teams',
            '35% reduction in paperwork delays',
            'Live dispatch visibility for managers',
        ],
    ],
    [
        'slug' => 'enterprise-portal-modernization',
        'title' => 'Enterprise Portal Modernization',
        'category' => 'Digital Transformation',
        'year' => '2024',
        'client' => 'Enterprise IT Division',
        'summary' => 'Modernized a legacy employee portal with secure SSO, responsive UI, and streamlined service requests.',
        'description' => 'A long-running intranet was holding back internal productivity. We rebuilt the experience with a modern component system, integrated enterprise SSO, and redesigned service request flows — reducing friction for thousands of employees while meeting strict security requirements.',
        'cover' => 'images/work-digital-transformation.png',
        'gallery' => [
            ['src' => 'images/work-digital-transformation.png', 'caption' => 'Employee home experience'],
            ['src' => 'images/work-it-consulting.png', 'caption' => 'Service request flow'],
            ['src' => 'images/work-software-development.png', 'caption' => 'Knowledge base redesign'],
        ],
        'tech_stack' => ['Laravel', 'Blade', 'Alpine.js', 'Azure AD', 'Azure'],
        'services' => ['Digital Transformation', 'UI/UX Design', 'Support & Maintenance'],
        'highlights' => [
            'SSO rollout across the organization',
            '60% faster service request completion',
            'Fully responsive internal experience',
        ],
    ],
    [
        'slug' => 'atlas-logistics-website',
        'title' => 'Atlas Logistics Website',
        'category' => 'Website',
        'year' => '2025',
        'client' => 'Atlas Logistics',
        'summary' => 'A conversion-focused marketing site with service pages, quote flows, and a CMS-backed blog for a regional logistics provider.',
        'description' => 'Atlas Logistics needed a modern web presence that could generate leads and communicate trust to enterprise shippers. We designed and built a fast, responsive marketing website with clear service positioning, location pages, an integrated quote request funnel, and a lightweight CMS for their team to publish updates without developer support.',
        'cover' => 'images/work-software-development.png',
        'gallery' => [
            ['src' => 'images/work-software-development.png', 'caption' => 'Homepage hero and services'],
            ['src' => 'images/work-it-consulting.png', 'caption' => 'Quote request flow'],
            ['src' => 'images/work-digital-transformation.png', 'caption' => 'Insights and resources hub'],
        ],
        'tech_stack' => ['Laravel', 'Blade', 'Alpine.js', 'Tailwind CSS', 'Cloudflare'],
        'services' => ['Web Development', 'UI/UX Design', 'Support & Maintenance'],
        'highlights' => [
            '45% increase in qualified quote submissions',
            'PageSpeed scores above 90 on mobile',
            'Marketing team can publish content independently',
        ],
    ],
    [
        'slug' => 'harbor-health-website',
        'title' => 'Harbor Health Website',
        'category' => 'Website',
        'year' => '2024',
        'client' => 'Harbor Health Clinics',
        'summary' => 'A patient-friendly clinic website with provider profiles, appointment booking, and accessible content for a multi-location healthcare group.',
        'description' => 'Harbor Health wanted a website that felt calm, credible, and easy to navigate for patients across multiple clinic locations. We delivered a branded experience with provider directories, service pages, online appointment requests, and accessibility-first layouts that meet WCAG guidelines while supporting the clinic group\'s growth into new regions.',
        'cover' => 'images/work-digital-transformation.png',
        'gallery' => [
            ['src' => 'images/work-digital-transformation.png', 'caption' => 'Clinic landing experience'],
            ['src' => 'images/work-software-development.png', 'caption' => 'Provider directory'],
            ['src' => 'images/work-it-consulting.png', 'caption' => 'Appointment request journey'],
        ],
        'tech_stack' => ['Laravel', 'Livewire', 'MySQL', 'Bootstrap', 'AWS'],
        'services' => ['Web Development', 'UI/UX Design', 'Cloud Solutions'],
        'highlights' => [
            'Accessible design across all patient touchpoints',
            'Unified site for 8 clinic locations',
            'Online appointment requests streamlined for staff',
        ],
    ],
];
